### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by sandnuggah** [faridco/rsox#6]
First off thanks for building this gem! This is the output from `gem install rsox`.

```
› gem install rsox
Building native extensions.  This could take a while...
ERROR:  Error installing rsox:
    ERROR: Failed to build gem native extension.

    /Users/***/.rbenv/versions/2.0.0-p0/bin/ruby extconf.rb
extconf.rb:3:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:3:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:4:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
checking for sox_format_init() in -lsox... yes
checking for sox.h... yes
creating Makefile

make
compiling rsox.c
rsox.c:254: error: expected ‘;’, ‘,’ or ‘)’ before ‘UNUSED’
rsox.c: In function ‘rsox_rubyblock_handler’:
rsox.c:270: error: ‘rsox_rubyblock_flow’ undeclared (first use in this function)
rsox.c:270: error: (Each undeclared identifier is reported only once
rsox.c:270: error: for each function it appears in.)
make: *** [rsox.o] Error 1
```

ruby --version
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.2.1]

gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

**Comment by srikanthsadhu** [comment]
I tried brew install sox and then gem install rsox still getting the below issue on Yosemite:

 gem install rsox

Fetching: rsox-0.0.2.gem (100%)
Building native extensions.  This could take a while...
/Users/sri/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:73: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040757
ERROR:  Error installing rsox:
    ERROR: Failed to build gem native extension.

```
/Users/sri/.rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20150109-85688-1mttcl2.rb extconf.rb
```

extconf.rb:3:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:3:in`<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:4:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
checking for sox_format_init() in -lsox... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/sri/.rvm/rubies/ruby-2.1.2/bin/ruby
    --with-rsox-dir
    --without-rsox-dir
    --with-rsox-include
    --without-rsox-include=${rsox-dir}/include
    --with-rsox-lib
    --without-rsox-lib=${rsox-dir}/lib
    --with-soxlib
    --without-soxlib

extconf failed, exit code 1

Gem files will remain installed in /Users/sri/.rvm/gems/ruby-2.1.2/gems/rsox-0.0.2 for inspection.
Results logged to /Users/sri/.rvm/gems/ruby-2.1.2/extensions/x86_64-darwin-13/2.1.0-static/rsox-0.0.2/gem_make.out
